### ISSUE TITLE
关于文档和推广的几个问题

### ISSUE THREAD

**Issue by fouber** [fex-team/fis-plus#10]
1. fis-plus的roadmap.path不能被定制，如果用户定制了roadmap.path，会导致几乎所有框架功能失效
1. README.md中列出的 ``Who uses FIS`` 项目都是基于fis的，而非fis-plus。
1. 如果用户参考现在的文档，安装了fis-plus，然后试图基于fis-plus去定制自己解决方案也是有很高成本的（要覆盖fis-plus中的配置，而且携带了一些不需要的插件）
1. 把fis的文档混在fis-plus中介绍，并且把fis-plus放到fis.baidu.com上推广，这些做法是出于什么考虑？

从成本上来说，用户接触fis只需要有nodejs环境，然后安装fis，可以当做工具来用，如果需要解决方案，可以参考 [php版](https://github.com/fouber/static-resource-management-system-demo) 和 [java版](https://github.com/fouber/fis-java-jsp) 两个例子。

而fis-plus用户除了有nodejs环境外，还要有java、php-cgi环境，安装fis-plus之外还要安装lights，然后学习fis-plus的规范、js框架、smarty框架，最后想要定制自己的解决方案的时候却发现其实应该学习的是fis，之前对于fis-plus的接触的最终意义只是被当做展现fis的最佳实践而已，这个从成本上来说不是更高么？

**Comment by xiangshouding** [comment]
已经解决
