### ISSUE TITLE
fisp page 中引入 widget 时，同名的 js 并没有自动引入

### ISSUE THREAD

**Issue by dancon** [fex-team/fis-plus#113]
page 中通过  `{%widget name="home:widget/abc/abc.tpl"%}`  引入 widget 时，widget/abc/ 目录下的同名  css 自动引入了，但是同名的 js 并没有自动引到页面中，这个是有什么配置控制的么？

**Comment by xiangshouding** [comment]
@dancon 你再自细看看，js 也应该是引入了的。

只是它是被组件化封装过的，需要调用 require 来执行里面暴露的函数。
