### ISSUE TITLE
期待 fis-plus 可以支持到 fis3

### ISSUE THREAD

**Issue by ystarlongzi** [fex-team/fis-plus#114]
如题，期待fis-plus团队的同学可以将 fis-plus 支持到 fis3，毕竟 fis3 在配置文件书写或者其他方面上，和 fis2 的差别还是挺大的。

@walterShen @2betop @xiangshouding @lily-zhangying

**Comment by xiangshouding** [comment]
@ystarlongzi fis3-smarty 可等价替换 fis-plus 你可以关注一下。

**Comment by ystarlongzi** [comment]
@xiangshouding 好的，谢谢！
