### ISSUE TITLE
发布出错

### ISSUE THREAD

**Issue by mi-le** [fex-team/fis-plus#123]
node版本v6.10.2
npm版本5.0.3
每次上传发布代码80%的情况会报错
错误信息：
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND www.explame.com www.explame:8020
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

20%的情况会发布成功。一直被困扰，求解答。

还有一个小建议，能不能修改部分代码只发布部分修改的，而不是修改一小部分，要把整个项目发布

**Comment by xiangshouding** [comment]
遇到这个问题一般是 你 deploy 的域名没能解析到 IP，可以换成 IP 试试。或者重试
