### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by tobeyouth** [fex-team/fis-plus#15]
在使用`fisp release`时，有很多时候其实是想看看合并之后的文件，但是使用了几次:
`fisp release -pd local`之后，发现require的文件并没有进行合并；只有在使用 `fisp release -pod local`时才会将require过来的文件合并到一起，但是文件又都压缩了...调试起来还挺麻烦的...

所以，能不能单独加个选项是合并文件的，不要把合并和压缩都做到一起？

**Comment by xiangshouding** [comment]
@tobeyouth 我们还有个项目是自动打包项目，不需要人工配包即可实现相当不错的打包结果。
