### ISSUE TITLE
调整fisp的命令行

### ISSUE THREAD

**Issue by xiangshouding** [fex-team/fis-plus#21]
- `fisp init` 主要做脚手架
- `fisp install` 主要下载组件

**Comment by xiangshouding** [comment]
@2betop

**Comment by Softor** [comment]
```
D:\code\nerve\nerve-update\merchant>fisp install widget -d ./widget/detail
Install start : Start download Component [pc-scaffold-widget@latest].
Install end : Finish download Component [pc-scaffold-widget@latest].
prompt: namespace:  nerve_merchant
prompt: file.basename:
```
请问，file.basename 是做什么用的？该如何设置？哪里有可参考的文档吗?

**Comment by xiangshouding** [comment]
@Softor  widget 的名字

**Comment by Softor** [comment]
谢谢您的及时回复。
我将file.basename设置成hello，在生成的detail.tpl文件中有提示说，调用widget的名称是hello.tpl。
也就是说，引用widget的名称跟物理文件名可以不同吗？
这个映射关系会记录在某个配置文件中？

**Comment by xiangshouding** [comment]
其实你想多了，应该是脚手架模板写得有点含糊，其实`file.basename`就是一个。。注释里面的全局变量，会替换为你输入的。

不过这块正在做调整，感谢你的使用。

**Comment by xiangshouding** [comment]
已经调整完
