### ISSUE TITLE
fisp server init 连接失败

### ISSUE THREAD

**Issue by zhangchen2397** [fex-team/fis-plus#23]
fisp server init 时连接失败，如下图

![fisp](https://cloud.githubusercontent.com/assets/1495896/5066618/27115db8-6e71-11e4-8fe3-b31340dff5ab.gif)

本地服务能正常起来，访问时始终都是

```
 Forward request " / " to file [ C:\Users\samczhang\AppData\Local\.fis-plus-tmp\www\index.php ].
```

**Comment by xiabingwu** [comment]
我也遇到这个问题了，你们是咋解决的呀

**Comment by xiabingwu** [comment]
这个文件我能手动下载，但是在cmd下下载不了 设置公司代理了也不行，但是能下github上的。
