### ISSUE TITLE
fisp数据模拟服务的问题

### ISSUE THREAD

**Issue by nighca** [fex-team/fis-plus#29]
好像每次服务启动后，在浏览中打开本地页面会，默认不使用本地的调试数据进行渲染（会使用空数据渲染出页面）？
需要使用文档中说的编辑测试数据的脚本（http://fis.baidu.com/fis-plus/userdoc/fis/%E6%9C%AC%E5%9C%B0%E8%B0%83%E8%AF%95%E6%95%B0%E6%8D%AE%E5%8A%9F%E8%83%BD ），在编辑界面中手动选择json后再点击render之后才正常（此后再次刷新页面数据都正常）。是需要配置什么参数，才能默认使用本地的数据吗？

P.S.
本地的fisp是使用的php server，模拟数据是test目录下的json文件。

**Comment by xiangshouding** [comment]
@nighca 了解，我看一下。

**Comment by nighca** [comment]
https://github.com/xiangshouding/fis-server-fisdata/blob/a2ee2b791ec29b5ae55994c9bcd52c33391adfc5/Manager.class.php#L45
是这个？看起来不好配置的样子

**Comment by xiangshouding** [comment]
@nighca 最近有点小忙，这块需要重撸。

**Comment by xiangshouding** [comment]
https://github.com/fis-dev/php-simulation-env

**Comment by nighca** [comment]
@xiangshouding 👍

**Comment by xiangshouding** [comment]
@nighca https://github.com/fis-dev/fis-plus-server-framework
