### ISSUE TITLE
fis-plus widget错误

### ISSUE THREAD

**Issue by luzuoquan** [fex-team/fis-plus#30]
{%widget name="home:widget/header/header.tpl"%}在页面引入了这个widget,但是报unable to locate resource "home:widget/header/header.tpl" 这个错误，widget需要安装相应的插件吗？

**Comment by qintengfei** [comment]
widget 是smarty的语法，可以检查一下是不是路径是否正确，可以用`fis server open` 去看

**Comment by luzuoquan** [comment]
在 fisp server 环境下面是正常的。 widget 是fisp 扩展的吧

**Comment by xiangshouding** [comment]
这个可以读一下文档 WIKI 或者是 oak.baidu.com/fis-plus

**Comment by luzuoquan** [comment]
smarty版本的问题，没有注意到我们项目中用到的是3.0.7，fisp 要>= 3.1.13才可以

**Comment by xiangshouding** [comment]
行吧~，了解了
