### ISSUE TITLE
如何在tpl中定位图片资源

### ISSUE THREAD

**Issue by Softor** [fex-team/fis-plus#32]
在tpl中引用loading.gif图片，release后，图片文件名称带了md5，可引用位置的路径指向的gif文件名不带md5。
如何是好？(根据官方文档提供的资源定位方式,uri也不好使)
```
<img class="list-loading" src="{%require name="module-name:static/img/loading.gif"%}">
```

**Comment by Softor** [comment]
这个问题原因在我。
由于我引用的img路径不存在，导致fisp原样呈现了我拼写的路径，我误以为没有添加md5的字符串。
错怪fisp了。

**Comment by g8up** [comment]
__补__ 如此引用到页面即可：
```
<img class="list-loading" src="/static/img/loading.gif">
```
参考：http://fex.baidu.com/fis-site/docs/more/fis-standard-location.html#在html中定位资源
