### ISSUE TITLE
资源请求404

### ISSUE THREAD

**Issue by trainGitHub** [fex-team/fis-plus#33]
本地调试时，有如下请求：
http://127.0.0.1:8080/static/common/css/common.css.map
请教  这.map是什么？ 怎么会404 ？

**Comment by xiangshouding** [comment]
重装，再试。

**Comment by trainGitHub** [comment]
fisp 已经更新到0.8.1 问题依旧。像common.css有两个请求一个是正常的http://127.0.0.1:8080/static/common/css/common.css，另一个请求是404 http://127.0.0.1:8080/static/common/css/common.css.map

还有就是这类的请求 http://127.0.0.1:8080/static/common/js/common:static/js/css.js，这我在fisp-amd-demo里看到应该是解决了的。该装的插件也装了。

请教大牛们，这些是啥问题？

**Comment by xiangshouding** [comment]
你提供下你的配置吧。

**Comment by trainGitHub** [comment]
common模块的配置是
fis.config.set('namespace', 'common');
fis.config.set('project.exclude', [
    /^\/plugin\/test\/.*/i
]);

fis.config.set('modules.postprocessor.tpl', 'amd');
fis.config.set('modules.postprocessor.js', 'amd');


fis.config.set('settings.postprocessor.amd', {
    //baseUrl: './widget',

    // 相当于别名或者链接
    paths: {
        avalon: 'common:static/js/avalon.shim.js',
        css: 'common:static/js/css.js',
        text: 'common:static/js/text.js'
    }
});


// 配置modules.parser插件
fis.config.set('modules.parser', {
    sass: 'sass',
    scss: 'sass'
    // 加入文件查找目录，发现这个include_paths 根本没用
    //include_paths: ['css/']
});

fis.config.set('roadmap.ext', {
    // scss后缀的文件将输出为css文件
    // 并且在parser之后的其他处理流程中被当做css文件处理
    sass: 'css',
    scss: 'css'
});

//项目排除掉_xxx.scss，这些属于框架文件，不用关心
fis.config.set('project.exclude', '**/_*.scss');

------------------------------------------------
home 模块的配置是

fis.config.set('namespace', 'home');
fis.config.set('modules.postprocessor.tpl', 'amd');
fis.config.set('modules.postprocessor.js', 'amd');

fis.config.set('settings.postprocessor.amd', {
    //baseUrl: './widget',
    paths: {
        oniui: 'common:widget/oniui/'
    }
});






// 配置modules.parser插件
fis.config.set('modules.parser', {
    sass: 'sass',
    scss: 'sass'
});

fis.config.set('roadmap.ext', {
    // scss后缀的文件将输出为css文件
    // 并且在parser之后的其他处理流程中被当做css文件处理
    sass: 'css',
    scss: 'css'
});

//项目排除掉_xxx.scss，这些属于框架文件，不用关心
fis.config.set('project.exclude', '**/_*.scss');

**Comment by trainGitHub** [comment]
|── README.md
├── common
│   ├── compass
│   │   ├── _css3.scss
│   │   ├── _functions.scss
│   │   ├── _layout.scss
│   │   ├── _reset-legacy.scss
│   │   ├── _reset.scss
│   │   ├── _support.scss
│   │   ├── _typography.scss
│   │   ├── _utilities.scss
│   │   ├── css3
│   │   │   ├── _animation.scss
│   │   │   ├── _appearance.scss
│   │   │   ├── _background-clip.scss
│   │   │   ├── _background-origin.scss
│   │   │   ├── _background-size.scss
│   │   │   ├── _border-radius.scss
│   │   │   ├── _box-shadow.scss
│   │   │   ├── _box-sizing.scss
│   │   │   ├── _box.scss
│   │   │   ├── _columns.scss
│   │   │   ├── _filter.scss
│   │   │   ├── _font-face.scss
│   │   │   ├── _hyphenation.scss
│   │   │   ├── _images.scss
│   │   │   ├── _inline-block.scss
│   │   │   ├── _opacity.scss
│   │   │   ├── _pie.scss
│   │   │   ├── _regions.scss
│   │   │   ├── _shared.scss
│   │   │   ├── _text-shadow.scss
│   │   │   ├── _transform-legacy.scss
│   │   │   ├── _transform.scss
│   │   │   ├── _transition.scss
│   │   │   └── _user-interface.scss
│   │   ├── functions
│   │   │   ├── _constants.scss
│   │   │   ├── _cross_browser_support.scss
│   │   │   ├── _display.scss
│   │   │   ├── _gradient_support.scss
│   │   │   └── _lists.scss
│   │   ├── layout
│   │   │   ├── _grid-background.scss
│   │   │   ├── _sticky-footer.scss
│   │   │   └── _stretching.scss
│   │   ├── reset
│   │   │   ├── _utilities-legacy.scss
│   │   │   └── _utilities.scss
│   │   ├── typography
│   │   │   ├── _links.scss
│   │   │   ├── _lists.scss
│   │   │   ├── _text.scss
│   │   │   ├── _vertical_rhythm.scss
│   │   │   ├── links
│   │   │   │   ├── _hover-link.scss
│   │   │   │   ├── _link-colors.scss
│   │   │   │   └── _unstyled-link.scss
│   │   │   ├── lists
│   │   │   │   ├── _bullets.scss
│   │   │   │   ├── _horizontal-list.scss
│   │   │   │   ├── _inline-block-list.scss
│   │   │   │   └── _inline-list.scss
│   │   │   └── text
│   │   │       ├── _ellipsis.scss
│   │   │       ├── _force-wrap.scss
│   │   │       ├── _nowrap.scss
│   │   │       └── _replacement.scss
│   │   └── utilities
│   │       ├── _color.scss
│   │       ├── _general.scss
│   │       ├── _links.scss
│   │       ├── _lists.scss
│   │       ├── _print.scss
│   │       ├── _sprites.scss
│   │       ├── _tables.scss
│   │       ├── _text.scss
│   │       ├── color
│   │       │   └── _contrast.scss
│   │       ├── general
│   │       │   ├── _clearfix.scss
│   │       │   ├── _float.scss
│   │       │   ├── _hacks.scss
│   │       │   ├── _min.scss
│   │       │   ├── _reset.scss
│   │       │   ├── _tabs.scss
│   │       │   └── _tag-cloud.scss
│   │       ├── links
│   │       │   ├── _hover-link.scss
│   │       │   ├── _link-colors.scss
│   │       │   └── _unstyled-link.scss
│   │       ├── lists
│   │       │   ├── _bullets.scss
│   │       │   ├── _horizontal-list.scss
│   │       │   ├── _inline-block-list.scss
│   │       │   └── _inline-list.scss
│   │       ├── sprites
│   │       │   ├── _base.scss
│   │       │   └── _sprite-img.scss
│   │       ├── tables
│   │       │   ├── _alternating-rows-and-columns.scss
│   │       │   ├── _borders.scss
│   │       │   └── _scaffolding.scss
│   │       └── text
│   │           ├── _ellipsis.scss
│   │           ├── _nowrap.scss
│   │           └── _replacement.scss
│   ├── fis-conf.js
│   ├── page
│   │   └── layout.tpl
│   ├── plugin
│   │   ├── FISResource.class.php
│   │   ├── README.md
│   │   ├── block.widget_inline.php
│   │   ├── compiler.body.php
│   │   ├── compiler.head.php
│   │   ├── compiler.html.php
│   │   ├── compiler.placeholder.php
│   │   ├── compiler.require.php
│   │   ├── compiler.script.php
│   │   ├── compiler.style.php
│   │   ├── compiler.uri.php
│   │   ├── compiler.widget.php
│   │   ├── function.http_header.php
│   │   ├── modifier.f_escape_callback.php
│   │   ├── modifier.f_escape_data.php
│   │   ├── modifier.f_escape_event.php
│   │   ├── modifier.f_escape_js.php
│   │   ├── modifier.f_escape_path.php
│   │   └── modifier.f_escape_xml.php
│   ├── static
│   │   ├── css
│   │   │   ├── common.scss
│   │   │   └── grid.scss
│   │   └── js
│   │       ├── avalon.js
│   │       ├── avalon.shim.js
│   │       ├── css.js
│   │       ├── esl.js
│   │       ├── mod-amd.js
│   │       ├── mod.js
│   │       ├── require.js
│   │       └── text.js
│   └── widget
│       ├── footer
│       │   └── footer.tpl
│       ├── header
│       │   ├── header.scss
│       │   ├── header.tpl
│       │   └── img
│       │       └── logo.png
│       └── oniui
│           ├── carousel
│           │   ├── carousel.css
│           │   ├── carousel.js
│           │   ├── carousel.tpl
│           │   └── images
│           │       ├── arrows-left-hover-icon.png
│           │       ├── arrows-left-icon.png
│           │       ├── arrows-right-hover-icon.png
│           │       └── arrows-right-icon.png
│           └── chameleon
│               ├── oniui-common.css
│               └── oniui-theme.css
├── home
│   ├── compass
│   │   ├── _css3.scss
│   │   ├── _functions.scss
│   │   ├── _layout.scss
│   │   ├── _reset-legacy.scss
│   │   ├── _reset.scss
│   │   ├── _support.scss
│   │   ├── _typography.scss
│   │   ├── _utilities.scss
│   │   ├── css3
│   │   │   ├── _animation.scss
│   │   │   ├── _appearance.scss
│   │   │   ├── _background-clip.scss
│   │   │   ├── _background-origin.scss
│   │   │   ├── _background-size.scss
│   │   │   ├── _border-radius.scss
│   │   │   ├── _box-shadow.scss
│   │   │   ├── _box-sizing.scss
│   │   │   ├── _box.scss
│   │   │   ├── _columns.scss
│   │   │   ├── _filter.scss
│   │   │   ├── _font-face.scss
│   │   │   ├── _hyphenation.scss
│   │   │   ├── _images.scss
│   │   │   ├── _inline-block.scss
│   │   │   ├── _opacity.scss
│   │   │   ├── _pie.scss
│   │   │   ├── _regions.scss
│   │   │   ├── _shared.scss
│   │   │   ├── _text-shadow.scss
│   │   │   ├── _transform-legacy.scss
│   │   │   ├── _transform.scss
│   │   │   ├── _transition.scss
│   │   │   └── _user-interface.scss
│   │   ├── functions
│   │   │   ├── _constants.scss
│   │   │   ├── _cross_browser_support.scss
│   │   │   ├── _display.scss
│   │   │   ├── _gradient_support.scss
│   │   │   └── _lists.scss
│   │   ├── layout
│   │   │   ├── _grid-background.scss
│   │   │   ├── _sticky-footer.scss
│   │   │   └── _stretching.scss
│   │   ├── reset
│   │   │   ├── _utilities-legacy.scss
│   │   │   └── _utilities.scss
│   │   ├── typography
│   │   │   ├── _links.scss
│   │   │   ├── _lists.scss
│   │   │   ├── _text.scss
│   │   │   ├── _vertical_rhythm.scss
│   │   │   ├── links
│   │   │   │   ├── _hover-link.scss
│   │   │   │   ├── _link-colors.scss
│   │   │   │   └── _unstyled-link.scss
│   │   │   ├── lists
│   │   │   │   ├── _bullets.scss
│   │   │   │   ├── _horizontal-list.scss
│   │   │   │   ├── _inline-block-list.scss
│   │   │   │   └── _inline-list.scss
│   │   │   └── text
│   │   │       ├── _ellipsis.scss
│   │   │       ├── _force-wrap.scss
│   │   │       ├── _nowrap.scss
│   │   │       └── _replacement.scss
│   │   └── utilities
│   │       ├── _color.scss
│   │       ├── _general.scss
│   │       ├── _links.scss
│   │       ├── _lists.scss
│   │       ├── _print.scss
│   │       ├── _sprites.scss
│   │       ├── _tables.scss
│   │       ├── _text.scss
│   │       ├── color
│   │       │   └── _contrast.scss
│   │       ├── general
│   │       │   ├── _clearfix.scss
│   │       │   ├── _float.scss
│   │       │   ├── _hacks.scss
│   │       │   ├── _min.scss
│   │       │   ├── _reset.scss
│   │       │   ├── _tabs.scss
│   │       │   └── _tag-cloud.scss
│   │       ├── links
│   │       │   ├── _hover-link.scss
│   │       │   ├── _link-colors.scss
│   │       │   └── _unstyled-link.scss
│   │       ├── lists
│   │       │   ├── _bullets.scss
│   │       │   ├── _horizontal-list.scss
│   │       │   ├── _inline-block-list.scss
│   │       │   └── _inline-list.scss
│   │       ├── sprites
│   │       │   ├── _base.scss
│   │       │   └── _sprite-img.scss
│   │       ├── tables
│   │       │   ├── _alternating-rows-and-columns.scss
│   │       │   ├── _borders.scss
│   │       │   └── _scaffolding.scss
│   │       └── text
│   │           ├── _ellipsis.scss
│   │           ├── _nowrap.scss
│   │           └── _replacement.scss
│   ├── fis-conf.js
│   ├── page
│   │   └── index.tpl
│   └── static
│       └── index
│           ├── img
│           │   ├── 2.png
│           │   ├── 3.png
│           │   ├── 4.png
│           │   ├── 5.png
│           │   ├── ad1.png
│           │   ├── ad2.png
│           │   ├── ad3.png
│           │   ├── b1.png
│           │   ├── b2.png
│           │   ├── b3.png
│           │   ├── brand.png
│           │   ├── brand2.png
│           │   ├── brand3.png
│           │   ├── brand4.png
│           │   ├── ic1.png
│           │   ├── icon
│           │   │   ├── i_arrow_right_grey_7x13.png
│           │   │   ├── i_jiao_down_red_13x7.png
│           │   │   └── i_jiao_right_green_7x13.png
│           │   ├── icon1.png
│           │   ├── point-red.png
│           │   └── start.png
│           ├── index.ascss
│           ├── index.css
│           └── index.js
└── package.json

**Comment by xiangshouding** [comment]
你升级下你的 `fis-parser-sass` 插件，是这个插件给 css 产出的 `source map` 导致此种情况。应该最新版本已经默认关掉了这个功能。

**Comment by trainGitHub** [comment]
fis-parser-sass@0.3.3 /......../node_modules/fis-parser-sass
└── fis-sass@3.1.2 (step@0.0.5, nan@1.6.2, chalk@0.5.1)

原来就是0.3.3,删了再装试了下还有那个map

**Comment by xiangshouding** [comment]
```
$ fisp server clean
$ fisp release -c
```

**Comment by trainGitHub** [comment]
clean了，然后把~/.fis-plus-tmp 目录下的文件都删了，重新编译还是有map

**Comment by xiangshouding** [comment]
浏览器清了吗？

**Comment by trainGitHub** [comment]
清了，如果暂时找不到办法，我能不能把.map 排除掉

**Comment by 2betop** [comment]
更新fis-plus
吧，老版本map文件没release
出来 

或者配置一下关了sourcemap

**Comment by trainGitHub** [comment]
fis-plus刚更新的。 2betop 出现啦 :) ,求教学。。
刚才那个 http://127.0.0.1:8080/static/common/js/common:static/js/css.js，用的requirejs。请求还是发出去了。然后 FISResource.class.php 我用的也是新的

**Comment by xiangshouding** [comment]
@2betop fis-plus 没有默认依赖 sass 啊。

**Comment by xiangshouding** [comment]
@trainGitHub 如果没有硬性要求，建议不要用 requirejs

**Comment by trainGitHub** [comment]
嗯，我不太确定mod-amd.js支不支持text!或者css!形式， 不过我试了用mod-amd.js那map还是老样子

**Comment by xiangshouding** [comment]
map是sass生成的，跟其他的没啥关系。

**Comment by trainGitHub** [comment]
@xiangshouding  求百度hi

**Comment by xiangshouding** [comment]
明显 requirejs 挖了一个大坑，然后看着别人跳，跳进去一匹死一匹，我不否认它带来的思路的影响力，但为它乱伸足表示担忧。

--

baidu hi： @相守鼎

**Comment by trainGitHub** [comment]
sourcemap 怎么配置呀？

**Comment by painty** [comment]
@trainGitHub 在`fis-conf.js`里面设置
```
fis.config.set('settings.parser.sass', {
    sourceMap:true
});
```
