### ISSUE TITLE
fis-plus 和 tomcat的关系。

### ISSUE THREAD

**Issue by shaohao2014** [fex-team/fis-plus#34]
1、运行fisp server start 之后，xampp里的tomcat服务器莫名其妙的启动，并开启了8080端口。
2、127.0.0.1:8080出现“No input file specified.”，也就是404错误。
3、为何fisp发布的内容和apche没有任何关系呢？

**Comment by hefangshi** [comment]
1. 你确定是tomcat服务器而不是xampp里面的php么？fisp server start会启动一个小型java server去调用php-cgi
2. 尝试 `fisp server init`
3. fisp发布的内容默认在 `fisp server open` 中
4. 建议先查阅一下文档 http://oak.baidu.com/fis-plus/document.html

**Comment by xiangshouding** [comment]
- `fisp server start` 还把 `tomcat` 给启动了？这是有多大能耐啊，要不 QQ 聊下？
