### ISSUE TITLE
修改了界定符的项目中，fisp release -o导致$smarty编译错误

### ISSUE THREAD

**Issue by morer** [fex-team/fis-plus#37]
各位大神，我们用fisp做前端项目构建，但$smarty的界定符{%%}很难用，被我们用smarty.conf修改成了{{}}，在没有进行项目的合并打包之前，一切OK，用fisp release可以正确的编译，但是在项目需要合并的时候，用fisp release -o进行编译后，打开原来的页面却报错了，错误信息如下：Fatal error: Uncaught exception 'SmartyCompilerException' with message 'Syntax Error in template &quot;C:\Users\Administrator\AppData\Local\.fis-plus-tmp\www\template\home\page\homePage.tpl&quot; on line 1 &quot;{{extends file=&amp;quot;./layout.tpl&amp;quot;}}{{block name=&amp;quot;body&amp;quot;}}........

**Comment by xiangshouding** [comment]
这是一个 Smarty 的 bug 导致的，详细见 #19

**Comment by morer** [comment]
经测试，在tpl中加入{*fix-smarty*}无用，没有解决该问题。在项目中，由于界定符为{{}}，我在{{block name="body"}}后添加{{fix-smarty}}，但是没有起到作用。在fisp release -o命令之前，我的模版文件一般每一行不长，但是用fisp release -o产生的模版文件第一行就比较长了。而下面的几行又不长，呵呵。

**Comment by morer** [comment]
我错了，其实是忘记了在fis-conf.js文件里面进行配置了

**Comment by fouber** [comment]
。。。。。。。

**Comment by xiangshouding** [comment]
。。。。。。。
