### ISSUE TITLE
Unexpected token: eof (undefined)

### ISSUE THREAD

**Issue by MarlonFan** [fex-team/fis-plus#39]
在release的过程中报出这个错误...完全不知道为啥啊...
optimizer.uglify-js: Unexpected token: eof (undefined)

**Comment by fouber** [comment]
@MarlonFan 

js压缩错误：非预期的结尾

是那个js文件的内容有问题

**Comment by MarlonFan** [comment]
非常感谢 我发现应该是雪碧插件的版本问题。对压缩的支持不太好。我把fis-plus由现在的最高级降到了0.7.2就没问题了

**Comment by xiangshouding** [comment]
@MarlonFan  what ? 雪碧插件操作的是 css ，而非 JS。请重新确认一下问题，再命令行添加 `--verbose` 参看哪个文件挂掉了。
