### ISSUE TITLE
FISP-0.7.2下 载入dojoJS报错

### ISSUE THREAD

**Issue by bzzkb** [fex-team/fis-plus#41]
dojo报：Error: defineAlreadyDefined
modjs报：Error: Cannot find module `[object Object]`
没找到问题出在哪，请教原因，thank you

**Comment by hefangshi** [comment]
define和require命令冲突了，dojo并不能和modjs一起使用

**Comment by bzzkb** [comment]
ok, 那就好解决了，thank you
