### ISSUE TITLE
请教在 fis plus 中，在 page 中直接引用的图片应该放在哪里？

### ISSUE THREAD

**Issue by unliu** [fex-team/fis-plus#43]
官方 demo，我试过放在 `/home/static/lib/img` 或 `/home/static/index` 里，发现都无法正确引用和定位。
只有放在一个 widget 目录中才能定位出来，但显然有违逻辑。
文档中只提到 css 和 js 的目录规范，没有提及图片。

**Comment by xiangshouding** [comment]
你路径是怎么写的？

**Comment by xiangshouding** [comment]
放在 static 下比较好，比如

```
/static/index/img/a.png
```

使用的时候

```html
<img src="/static/index/img/a.png" />
```

**Comment by unliu** [comment]
我把文件放在 `/home/static/index/img/a.png` 或  `/static/index/img/a.png`下，
在`/home/page/index.tpl`中用`<img src="/static/index/img/a.png" />`，都引用不到。

**Comment by xiangshouding** [comment]
把 代码打包发给我 我看看，目测是你把配置文件写坏了。

**Comment by unliu** [comment]
汗，这次是我文件后缀错了。
我发现之前原因是引用方式写成了 `<img src="static/index/img/a.png" />`，没有绝对定位就会引用不到。
谢谢帮助！

**Comment by xiangshouding** [comment]
我说呢，我都开始怀疑上帝了。

**Comment by g8up** [comment]
遇到了相同问题，我一般都是先试图这样：
`{%uri name="module_name:/static/img/a.png%}`
可是并不如愿，对 uri 这个东西，官方文档应该多说几句。

**Comment by xiangshouding** [comment]
@g8up 已经文档明确说过了，id，后面的subpath是不能带 `/`

`module_name:static/img/a.png`

另外，图片是不会进入 map.json 如果想用 smarty 插件读到具体路径必须让图片也进入 map.json

**Comment by g8up** [comment]
@xiangshouding ,在 tpl 文件中，支持通过 uri 访问本模块的静态图片吗？比如：
`
{%uri name="module_name:static/img/stuff.png%}
`

**Comment by 2betop** [comment]
支持，但是你需要确保这个资源记录在了生成的 map.json 文件里面。

**Comment by SylviaF** [comment]
@xiangshouding 有办法配置让图片也进入 map.json吗
