### ISSUE TITLE
fisp server start --type=node

### ISSUE THREAD

**Issue by PetersonLian** [fex-team/fis-plus#45]
我按照文档。敲入如下命令：  

    fisp release -r common  
    fisp release -r home  
    fisp server start  

然后报错，意思是java未安装（属实）  
然后我又敲入如下命令：  

    fisp release -r common  
    fisp release -r home  
    fisp server start  --type=node  

服务器启动，页面也出来了，可是页面根本没有任何css，整个页面的样子（更ftp那种类似），只是单纯显示文件目录结构，感觉就是个ftp。跟文档中的显示结果不一致。这是正常行为？  
我想请问，能否不需要安装java？  
我的系统是windows64位，fisp -v == 0.8.4。

**Comment by xiangshouding** [comment]
no，java 是必须要的，除非你不用 fis-plus 提供的 server 做调试服务器。

**Comment by PetersonLian** [comment]
@xiangshouding 好。安装java之后可用。已测
