### ISSUE TITLE
.tpl文件是什么语法

### ISSUE THREAD

**Issue by PetersonLian** [fex-team/fis-plus#46]
很菜鸟的问题，本来不想new一个issue的，可是不知道还有什么其它渠道。  
.tpl的模板文件是smarty的语法吗？

**Comment by xiangshouding** [comment]
Smarty

**Comment by Softor** [comment]
@PetersonLian ,官方文档：http://oak.baidu.com/fis-plus/document.html
第一段就有提及 Smarty

**Comment by PetersonLian** [comment]
@Softor 是的。只是确认下
