### ISSUE TITLE
require 引入外部资源在资源后面加上类似#符号之后编译之后无法引进js

### ISSUE THREAD

**Issue by DeyuanTan** [fex-team/fis-plus#47]
![image](https://cloud.githubusercontent.com/assets/8966624/7134317/5fd084d6-e2ce-11e4-9f4c-1bb3ab510b69.png)  require 引入外部资源在资源后面加上类似#符号之后编译之后无法引进js

**Comment by ligaofeng0901** [comment]
同遇到类似问题， require了一个外部的js sdk, sdk不是以.js结尾，编译时被直接忽略了。 目测是按照文件后缀名区分资源类型的，但有时候后缀名无法提供文件类型，应该有一个参数来指示文件类型，不知道目前官方是否有解决方案。

**Comment by xiangshouding** [comment]
这个嘛。。

```html
<script src="xxxx"></script>
{%/body%}
```
done

**Comment by ligaofeng0901** [comment]
@xiangshouding  这样的话，貌似fis编译时就不会再调整js的顺序了

**Comment by xiangshouding** [comment]
@ligaofeng0901 是啊，这个需求也是可以支持的；

```
{%require src="xxx" type="js"%}
```
什么的；

**Comment by xiangshouding** [comment]
fex-team/fis-plus-smarty-plugin@4faa774aa0a73b7da76e6bd449119b18bc4563bc

嗯，就这样，没测，你俩用着看吧；

**Comment by DeyuanTan** [comment]
![image](https://cloud.githubusercontent.com/assets/8966624/7297678/e2443bb2-e9fc-11e4-99f2-74f60360a42c.png)
我的需求相对简单，只需要引入带#，所以偷懒只改了正则

**Comment by xiangshouding** [comment]
@DeyuanTan 嗯，也行；
