### ISSUE TITLE
mac环境下 fis-plus测试数据目录中的php文件不能require上级文件

### ISSUE THREAD

**Issue by hylin** [fex-team/fis-plus#48]
windows中没这个问题，mac中会出现这个现象：
经测试，可以require当前目录和下级目录中的文件，但是不能require上级目录中文件。
test/common.php
test/job/index.php
test/job/common1.php
test/job/sub/common2.php
如上的目录结构，在job/index.php中，可以require("common1.php"),require("sub/common2.php")。
但是不能require("../common.php")。会报错：Failed opening required

**Comment by xiangshouding** [comment]
```php
require(dirname(dirname(__FILE__)) . '/common.php');
```

**Comment by hylin** [comment]
@xiangshouding 不能用相对路径，必须用绝对路径？

**Comment by xiangshouding** [comment]
@hylin 不清楚，我从来只用绝对路径。

**Comment by hylin** [comment]
@xiangshouding 我们项目中同样的代码require('/test/crawler/page/common.php');
在windows下正常的，但是mac会有这个问题Failed opening required
然后我就测试出来，无法写相对路径require上级目录文件
绝对路径和你说的一样，我测试中是正常的
感觉还是fis处理相对路径上有点问题

**Comment by xiangshouding** [comment]
@hylin 这个跟 fis 处理没啥关系，这时候已经是在一个测试环境中了，fis 编译也不会修改 test 下的 require 的路径；只是可能俩系统下的 PHP 执行的时候有点不太一样；
