### ISSUE TITLE
fis安装后报错

### ISSUE THREAD

**Issue by jinjiang2009** [fex-team/fis-plus#49]
./fis -v  报错/usr/bin/env: node: No such file or directory

**Comment by fouber** [comment]
@jinjiang2009 

fis是全局安装，然后执行 ``fis -v``，而不是 ``./fis -v``

**Comment by jinjiang2009** [comment]
我在node官网下载的包,然后 ./npm install -g fis这样安装的fis,我的node不是全局安装的

**Comment by xiangshouding** [comment]
改一下 bin/fis 最上面的那行行注释

**Comment by jinjiang2009** [comment]
改成我node的安装目录吗,/usr/local/nodejs/bin/node这样吗

**Comment by xiangshouding** [comment]
@jinjiang2009 是的

**Comment by jinjiang2009** [comment]
还有一点我不太清楚,fis怎么和php结合开发,部署在服务器上,是lnmp环境还是node环境

**Comment by xiangshouding** [comment]
没有专门写一篇，不过你可以参考

- http://www.orrafy.com/posts/fisbook/fisp-online-smarty/
- https://github.com/fex-team/fis/issues/390

**Comment by jinjiang2009** [comment]
多谢,给力

**Comment by jinjiang2009** [comment]
fis release -o 时候报错 node-pngcrush does not support your node v0.12.2, report it to https://github.com/xiangshouding/node-pngcrush/issues

**Comment by xiangshouding** [comment]
@jinjiang2009 啥系统，多少位的？

**Comment by jinjiang2009** [comment]
centos 32位,这个是个提示,实际操作中没什么影响

**Comment by xiangshouding** [comment]
其实，唉，我没有给 32 位机器编译二进制包；当时没找到机器，自己的虚拟机又坏了。。

**Comment by xiangshouding** [comment]
@jinjiang2009 你可以暂时关闭图片压缩，不影响其他功能；

```js
fis.config.del('modules.optimizer.png');
```
