### ISSUE TITLE
安装pc-demo报错

### ISSUE THREAD

**Issue by fancyboynet** [fex-team/fis-plus#54]
提示：
Install start : Start download Component [pc-demo@latest]. 
Install failed : Install [pc-demo@latest] failed

**Comment by xiangshouding** [comment]
```
 fisp init pc-demo
Install start : Start download Component [pc-demo@latest].
Install end : Finish download Component [pc-demo@latest].
```
我这块是 ok 的；

你也可以到此处  https://github.com/fex-team/fis-plus-pc-demo 下载；

**Comment by fancyboynet** [comment]
fisp init pc-demo是好的
lights install pc-demo不行

**Comment by xiangshouding** [comment]
OK，我看看
