### ISSUE TITLE
f_escape_xml 在本地有用，但是发布到测试服务器无效

### ISSUE THREAD

**Issue by morer** [fex-team/fis-plus#56]
我在fis-conf.js里面配置了html unescape插件
fis.config.set('modules.optimizer.tpl', 'smarty-xss');
fis.config.set('settings.optimizer.smarty-xss', {
    'escapeMap' : {
        //'js' : 'f_escape_js',  //配置js_escape指定js转义插件的名称
        'html' : 'f_escape_xml' //配置html_escape指定对于xml转义插件的名称
        //'data' : 'f_escape_data', //配置data_escape指定data转义插件的名称
        //'path' : 'f_escape_path', //配置path_escape指定url、path转义插件的名称
        //'event' : 'f_escape_event', //配置event_escape指定event转义插件的名称
        //'no_escape' : 'escape:none' //不需要添加转义的变量标志
    },
    'xssSafeVars' :[          //配置白名单
        'fis_safe'      //支持正则
    ]
});
这个在本地测试是OK的，但是上传到测试服务器就没用了。

**Comment by hefangshi** [comment]
可以提供一些更详细的信息，比如

1. 上传到测试服务器后没用是怎么确定的？模板里面没有自动添加filter？还是执行结果不对？
2. 如何上传到测试服务器的，上传测试服务器时有加-o参数么？

**Comment by morer** [comment]
我弄混了，我将 'html' : 'f_escape_xml'修改成为 'html' : ''就行了，也就是不转义就行了。
