### ISSUE TITLE
今天用fis+遇到个问题 不知道大大们能不能实现 或者说有这个功能我不知道告知下

### ISSUE THREAD

**Issue by w2230030100** [fex-team/fis-plus#58]
就是我举个例子 
比如说有个第一级的模版layout.tpl里面有个变量$description
我在test文件夹下建立一个layout.php给layout.tpl中的$description赋值了一个虚拟的数据 这样如果再访问layout.tpl的时候应该就又数据了吧 目前是这个样子的
我想要这样 比如说有个继承了layout.tpl的模板文件能不能也把虚拟的$description数据也能继承过来 目前我试验是继承不过来的 必须重新赋值一下 最好是继承过来后如果我重新赋值$description就会覆盖前者的数据 大大们看可行么

**Comment by xiangshouding** [comment]
测试数据是 php 的文件，请自由发挥；

layout 理论上来说不会被单独访问;

你可以弄一个叫 common.php 的文件来存放公共数据，后在其他数据文件中 require 这个文件，并把其中的数据 merge 给 `$fis_data` 变量即可；
