### ISSUE TITLE
首先谢谢大大对我的一些蛋疼问题的回答 但是我还是有些问题请教

### ISSUE THREAD

**Issue by w2230030100** [fex-team/fis-plus#61]
就是我遇到这样一个问题 我很多项目都用到了jquery 
比如我site下的两个module下的widget都用到了jquery 我不想分别在模块下下载jquery 我想统一引入common下的jquery 
但是common下的jquery引入我得这么引入
```var $ = require("common:components/jquery/jquery.js"); ```
我想简化一下引入的字符串 比如只要这样
```var $ = require("jquery");```
或者
```var $=require("common:jquery");```
可以实现吗

**Comment by w2230030100** [comment]
或者说能不能设置个别名 就想seajs那种 “xxx”：“xx/xx/xx/xx.js” 然后引用xxx就可以调用js了

**Comment by 2betop** [comment]
可以的！

```javascript
fis.config.set('settings.preprocessor.components.paths', {
    'jquery': 'common:components/jquery/jquery.js'
});
```

**Comment by w2230030100** [comment]
@2betop 谢谢 请问大大这些资料哪里有看啊 我想学习下

**Comment by w2230030100** [comment]
@2betop 谢谢 请问大大这些资料哪里有看啊 我想学习下

**Comment by xiangshouding** [comment]
@w2230030100 
- 看文档 http://oak.baidu.com/fis-plus
- 看源码 [fex-team/fis-plus](/fex-team/fis-plus)
- 看依赖的插件 https://github.com/fex-team/fis-plus/blob/master/package.json#L18-L30

**Comment by w2230030100** [comment]
@xiangshouding 就是我如果想看到类似这种配置的文档应该去哪里找
fis.config.set('settings.preprocessor.components.paths', {
    'jquery': 'common:components/jquery/jquery.js'
});
这种的

**Comment by 2betop** [comment]
https://github.com/fex-team/fis-preprocessor-components

**Comment by xiangshouding** [comment]
@w2230030100 

- preprocessor 如果你看了文档的话你知道这是个插件类型，那么这个插件的名字叫 components，那么按照 fis 对插件的规范，这个插件在 npm 上的包是 `fis-preprocessor-components`
- 找到这个插件就可以看里面的 README.md 了

当然你要问，你们这破玩意儿找半天才能找得到谁稀罕用？

那么这个问题就在于为什么这么高大上的功能没有出现在官网文档里面，因为我举着这种做法是不恰当的；

当我看到

```js
require('common:components/jquery/jquery.js');
```

的时候，我立马就知道用的是哪个 `jquery`，而当我看到 `require('jquery')` 时我不知道用的是哪个 jquery，因为可能我源码里面有多个；

那么你的出发点可能是对于书写起来快这个点；而我的出发点是维护起来方便这个点；

最终我选择了后者，因为排查问题异常痛苦，我还是悠着点来；

**Comment by w2230030100** [comment]
谢谢大大们的无私回答 后者确实维护要方便很多
代码的那个灰框框我知道咋弄了
话说哪个小圆点怎么打出来的 嘿嘿

**Comment by xiangshouding** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by yanhaijing** [comment]
fisp 是可以直接用fis-components是吧
