### ISSUE TITLE
使用autopack插件的简单模式时候遇到的一个问题。

### ISSUE THREAD

**Issue by hanan198501** [fex-team/fis-plus#69]
场景如下：
a.tpl引入a.js, c.js, d.js
b.tpl引入b.js, c.js, d.js

最后打包结果是：
a.js,b.js,c.js,d.js被打包成了一个文件：abcd.js
a.tpl和b.tpl的引用都变成了abcd.js

这样的话，a.tpl多了b.js的代码，b.tpl多了a.js的代码。在我们的项目，导致了一些代码上的冲突。如何解决呢？

**Comment by xiangshouding** [comment]
@hanan198501 请联系，涛哥。
