### ISSUE TITLE
fisp server init的时候提示下载latest.tar失败，提示超时，是什么原因呢

### ISSUE THREAD

**Issue by ElaineHee** [fex-team/fis-plus#72]
如题，提示error如下图：

![001](https://cloud.githubusercontent.com/assets/5765512/8797741/08a5e148-2fd0-11e5-965b-cf9d7b4996a0.jpg)

**Comment by ElaineHee** [comment]
checking php-cgi support： unsupported php-cgi environment
这个问题有人知道么？

**Comment by xiangshouding** [comment]
fex-team.github.com/fis-plus  文档地址

php-cgi 安装了吗？

**Comment by ElaineHee** [comment]
1. 安装了，根据文档地址，初始化文档地址的时候，提示下载链接超时（从昨天开始就一直这样），错误如下：

[ERROR] unable to download component [pc@latest] from [http://fis.baidu.com/repos/server/pc/latest.tar], error [connect ETIMEDOUT]



2. demo下载也是失败的，所以我从之前的项目拷贝了一份过来

3. 可以发布，发布是成功的

4. 服务器启动失败，提示不支持的java版本（v1.4.2 但是我之前的项目也是用的这个版本java），错误提示如下：

checking java support : java not support!v1.4.2

**Comment by ElaineHee** [comment]
checking java support : v1.6.0
checking php-cgi support : unsupported php-cgi environment

**Comment by ElaineHee** [comment]
安装了odp环境，启动了php-cgi，启动信息如下：
Shutting down php_fpm .done
Starting php_fpm done

**Comment by ElaineHee** [comment]
麻烦同学回复了铪，今天来公司之后我重新整理了一下环境变量，安装了新版本的java，fisp server start启动成功。

但是页面展示的时候，php报错提示html标签未知，具体信息如下：
![003](https://cloud.githubusercontent.com/assets/5765512/8817083/62f61762-3061-11e5-8244-0970b39f680d.jpg)

**Comment by ElaineHee** [comment]
问题已经解决，自己mark一下
odp需要在config/smarty.conf里面修改：模板目录，模板编译目录，配置目录，插件目录
