### ISSUE TITLE
fis server start 后报错

### ISSUE THREAD

**Issue by triumphalism** [fex-team/fis-plus#75]
F:\>fisp server start

 [ERROR] fail to execute `tasklist` command, please add your system path (eg: C:
\Windows\system32, you should replace `C` with your system disk) in %PATH%

**Comment by triumphalism** [comment]
java 和php-cgi已经安装好了。也初始化环境了，但是开启服务器的时候，老是报错，请教下这个问题怎么解决。

**Comment by xiangshouding** [comment]
system32 这个文件夹需要设置到 PATH 里面

**Comment by xiangshouding** [comment]
system32 这个文件夹需要设置到 PATH 里面

**Comment by xiangshouding** [comment]
system32 这个文件夹需要设置到 PATH 里面

**Comment by triumphalism** [comment]
已经解决，万分感谢。
