### ISSUE TITLE
fisp模板开发后倒底是如何和php整合的

### ISSUE THREAD

**Issue by lenxeon** [fex-team/fis-plus#86]
这个还是一直没有搞懂啊，最近试了下这个demo，迫切想将它变成动态的，而不是现在写死的测试数据。
我的项目是java的，通过http提供json数据，想用php通过http请求java的api,再结合fisp开发。谁给点意见，谢谢。

**Comment by xiangshouding** [comment]
http://www.orrafy.com/posts/fisbook/fisp-online-smarty/
