### ISSUE TITLE
fisp release 具体命令咨询

### ISSUE THREAD

**Issue by ElaineHee** [fex-team/fis-plus#90]
1. watch 命令是监控项目的变化，监控结果在哪里查看？
2. clean 清洁编译缓存，如果没有清理会怎样？
3. root设置项目根目录，这个是做什么的？
4. file 设置fis-conf文件，这个不是固定位置么？

**Comment by xiangshouding** [comment]
0. 结果就是你设定 release 的地方，如果是默认 release，那么会 release 到本地默认的一个 web 服务根目录吓。可以用 fisp server open 打开
0. clean 缓存只是在可能出现问题的或者缓存过多的情况下才执行，比如有些同学很长时间不处理，缓存就达到好几个G
0. root 根目录这个，设定项目根目录的意思，编译多个模块就会很方便了。

  比如你有三模块，a，b，c；这时候你不需要 cd 到这些模块的路径下，也可以做编译了。

  fisp release -r a
  fisp release -r b
  fisp release -r c

0. 默认一个配置文件，但也可以有多个配置文件，或者配置文件的名字可以不相同，这是一般命令行软件的做法。可以根据不同的情况去 -f 不同的配置文件，看用户需求来定。

**Comment by ElaineHee** [comment]
非常感谢回答
