### ISSUE TITLE
本地调试出现异常：SmartyCompilerException

### ISSUE THREAD

**Issue by g8up** [fex-team/fis-plus#92]
`
SmartyCompilerException: Syntax Error in template "XXX.tpl" on line 13 "{%html framework=&quot;xxx:static/js/libs/mod.js&quot;%}" unknown tag "html" in C:\Users\xxx\AppData\Local\.fis-plus-tmp\www\smarty\sysplugins\smarty_internal_templatecompilerbase.php on line 665
`
使用的发布命令：`fisp release -cr ./`
感觉像是 smarty 出了问题。
请教如何解决呢？

**Comment by xiangshouding** [comment]
我应该在稳定中说了插件的重要性，你这个表象是缺　FIS 　提供的　Smarty 插件；例子的　common　目录下有个　plugin 子目录，copy 一份放到你的模块下，重新　release 一下；
