### ISSUE TITLE
安装php-cgi报错

### ISSUE THREAD

**Issue by HellowVirgil** [fex-team/fis-plus#95]
使用`$ brew install php55 --with-cgi`安装php-cgi报以下错误

```
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

**Comment by zhangtao07** [comment]
可以用 xampp 方法试试https://gist.github.com/xiangshouding/9359739 ，不过10.11是不稳定版本吧，可能很多东西安装不上的

**Comment by HellowVirgil** [comment]
@zhangtao07 嗯，XAMPP可以了，thx

**Comment by Anikinly** [comment]
@HellowVirgil  XAMPP 安装以后 怎么添加路径到全局变量里面呢  找不到这个软件对应的路径
