### ISSUE TITLE
fisp server init error

### ISSUE THREAD

**Issue by var-mach** [fex-team/fis-plus#96]
install [pc@latest]
 [ERROR] unable to download component [smarty@latest] from [http://fis.baidu.com/repos/server/smarty/latest.tar], error [302]
但是直接输入这个链接（http://fis.baidu.com/repos/server/smarty/latest.tar）可以下载，请问是什么原因

**Comment by xiangshouding** [comment]
这个应该是网络问题，点击这个链接看看是否能下载到东西。

**Comment by var-mach** [comment]
不是呀，直接点连接可以下载的

**Comment by var-mach** [comment]
确实是网络问题 换一个地方就OK了
