### ISSUE TITLE
define is not defined

### ISSUE THREAD

**Issue by koalaqinqin** [fex-team/fis-plus#99]
发布后，启动服务器，显示，如下错误
`mod.js:1 Uncaught ReferenceError: define is not defined`
下边这句话的地方报错
`define('common:static/mod.js', [],function(require, exports, module){ /**`

**Comment by xiangshouding** [comment]
这个是啥，fis 编译出的结果？
2016年5月2日 下午11:05，"琴琴" <notifications@github.com>写道：

**Comment by koalaqinqin** [comment]
这个是pc-demo那个例子，我运行后，报错，打开source，看到是给mod.js加了一个头`define('common:static/mod.js', [],function(require, exports, module){ /**`但是显示`define is not defined`，还有那个例子加载了nav.js,是require进去的，也显示`require is not defined`，不知道是什么原因造成的

**Comment by koalaqinqin** [comment]
应该是mod.js没有引入，应该是引入mod.js过后才有define这个函数吧，但是编译过后为什么给mod.js也加了这个定义模块的头呢

**Comment by xiangshouding** [comment]
哦，那你配置估计有问题

**Comment by koalaqinqin** [comment]
找到问题了，是跟我之前安装的一个fis模块冲突了，之前用的那个是用的sea.js，把之前的那个删除，重装了一下fis-plus，没有报错了。非常感谢！
